### ISSUE TITLE
Homebridge is not registering the plugin

### ISSUE THREAD

**Issue by liam923** [jnovack/homebridge-better-http-rgb#17]
For a while, it was working with no issue. However, it no longer shows up as one of the plugins that registers when homebridge starts.

**Comment by liam923** [comment]
I looked into it more, and I am getting this error:

    [11/22/2017, 12:33:04 PM] ERROR LOADING PLUGIN homebridge-better-http-rgb:
    [11/22/2017, 12:33:04 PM] /usr/local/lib/node_modules/homebridge-better-http-rg$
    m/dule.ezpovts = {
    ^^^^^^^^^^^^^^
    ReferenceError: Invalid left-hand side in assignment
        at createScript (vm.js:56:10)
        at Object.runInThisContext (vm.js:97:10)
        at Module._compile (module.js:542:28)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-better-http-rgb/node_modules/asn1/lib/ber/index.js:4:13)

**Comment by jnovack** [comment]
What did you upgrade? Things don't "magically" break?
